### ISSUE TITLE
Use tiff package from CRAN

### ISSUE THREAD

**Issue by AB-Kent** [christianrickert/CU-HIMSR#1]
The Akoya TIFF package is no longer needed (or supported) by phenoptr. The version of {tiff} on CRAN has been updated with the required functionality. So this line is no longer needed.
https://github.com/christianrickert/CU-HIMSR/blob/31cc35c8f56bddec7a3c3227b65ebedd84caec9d/install_phenoptr-Reports.R#L33

**Comment by christianrickert** [comment]
Thanks @AB-Kent, I've updated the installation repo.
Now it's time to archive the [Akoya TIFF repo](https://github.com/akoyabio/tiff/tree/master)? 😄

**Comment by AB-Kent** [comment]
Good idea, done!
